name: Tiny Security Scan

on:
  workflow_dispatch:

jobs:
  tiny-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tiny scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: '.'
          severity: 'CRITICAL'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
